### ISSUE TITLE
Getting error ValueError("Unknown label type: %r" % y) with a different dataset

### ISSUE THREAD

**Issue by shaktisd** [wendykan/DeepLearningMovies#3]
I slightly changed the input dataformat, instead of 0 and 1 I replaced with BUY , SELL, HOLD, but I am getting the below exception, can you please tell me whats needs to be changed to train the data with the below format.

```
id      sentiment       review
0       SELL    Not a good stock don't buy.
1       BUY     Looks good , go ahead and buy .
2       HOLD   Looks okay.
```

Training the random forest (this may take a while)...
Traceback (most recent call last):
  File "BagOfWords.py", line 81, in <module>
    forest = forest.fit( train_data_features, train["sentiment"] )
  File "/usr/local/lib/python2.7/dist-packages/sklearn/ensemble/forest.py", line 235, in fit
    y, expanded_class_weight = self._validate_y_class_weight(y)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/ensemble/forest.py", line 421, in _validate_y_class_weight
    check_classification_targets(y)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/utils/multiclass.py", line 173, in check_classification_targets
    raise ValueError("Unknown label type: %r" % y)
ValueError: Unknown label type: array([[nan],

**Comment by shaktisd** [comment]
just made the labels to lowercase
